import type { Theme } from './types';

export const THEMES: Theme[] = [
  {
    id: '1.1',
    title: 'Danger teaching',
    chapters: [
      { id: '1.1.01', name: 'Basic forms of traffic behavior', totalQuestions: 15, completedQuestions: 0 },
      { id: '1.1.02', name: 'Behavior towards pedestrians', totalQuestions: 57, completedQuestions: 0 },
      { id: '1.1.03', name: 'Road and weather conditions', totalQuestions: 22, completedQuestions: 0 },
      { id: '1.1.04', name: 'Darkness and poor visibility', totalQuestions: 7, completedQuestions: 0 },
      { id: '1.1.05', name: 'Speed', totalQuestions: 6, completedQuestions: 0 },
      { id: '1.1.06', name: 'Overtaking', totalQuestions: 21, completedQuestions: 0 },
      { id: '1.1.07', name: 'Special traffic situations', totalQuestions: 84, completedQuestions: 0 },
      { id: '1.1.09', name: 'Alcohol, drugs, medication', totalQuestions: 25, completedQuestions: 0 },
      { id: '1.1.10', name: 'Health risks', totalQuestions: 2, completedQuestions: 0 },
    ],
  },
  {
    id: '1.2',
    title: 'Behaviour in traffic',
    chapters: [
      { id: '1.2.01', name: 'Basic rules about behaviour in road traffic', totalQuestions: 2, completedQuestions: 0 },
      { id: '1.2.02', name: 'Road use', totalQuestions: 9, completedQuestions: 0 },
      { id: '1.2.03', name: 'Speed', totalQuestions: 9, completedQuestions: 0 },
      { id: '1.2.04', name: 'Distance', totalQuestions: 4, completedQuestions: 0 },
      { id: '1.2.05', name: 'Overtaking', totalQuestions: 23, completedQuestions: 0 },
      { id: '1.2.06', name: 'Passing', totalQuestions: 6, completedQuestions: 0 },
      { id: '1.2.07', name: 'Use of lanes by motor vehicles', totalQuestions: 8, completedQuestions: 0 },
      { id: '1.2.09', name: 'Turning, turning and reversing', totalQuestions: 48, completedQuestions: 0 },
      { id: '1.2.10', name: 'Entering and starting', totalQuestions: 9, completedQuestions: 0 },
      { id: '1.2.11', name: 'Special traffic situations', totalQuestions: 18, completedQuestions: 0 },
      { id: '1.2.12', name: 'Stopping and parking', totalQuestions: 27, completedQuestions: 0 },
      { id: '1.2.16', name: 'Warning signs', totalQuestions: 6, completedQuestions: 0 },
      { id: '1.2.17', name: 'Lighting', totalQuestions: 3, completedQuestions: 0 },
      { id: '1.2.19', name: 'Level crossings', totalQuestions: 23, completedQuestions: 0 },
      { id: '1.2.20', name: 'Public transport and school buses', totalQuestions: 16, completedQuestions: 0 },
      { id: '1.2.22', name: 'Load', totalQuestions: 7, completedQuestions: 0 },
      { id: '1.2.23', name: 'Other duties of the driver', totalQuestions: 6, completedQuestions: 0 },
      { id: '1.2.26', name: 'Behaviour at pedestrian crossings and towards pedestrians', totalQuestions: 17, completedQuestions: 0 },
      { id: '1.2.34', name: 'Accident', totalQuestions: 18, completedQuestions: 0 },
      { id: '1.2.36', name: 'Signs and instructions from police officers', totalQuestions: 15, completedQuestions: 0 },
      { id: '1.2.37', name: 'Variable and steady light signals', totalQuestions: 20, completedQuestions: 0 },
      { id: '1.2.38', name: 'Blue flashing light and yellow flashing light', totalQuestions: 6, completedQuestions: 0 },
    ],
  },
  {
    id: '1.3',
    title: 'Priority',
    chapters: [
      { id: '1.3.01', name: 'Priority', totalQuestions: 54, completedQuestions: 0 },
    ],
  },
  {
    id: '1.4',
    title: 'Road sign',
    chapters: [
      { id: '1.4.40', name: 'Danger sign', totalQuestions: 53, completedQuestions: 0 },
      { id: '1.4.41', name: 'Regulatory sign', totalQuestions: 88, completedQuestions: 0 },
      { id: '1.4.42', name: 'Directional sign', totalQuestions: 40, completedQuestions: 0 },
      { id: '1.4.43', name: 'Traffic facilities', totalQuestions: 1, completedQuestions: 0 },
    ],
  },
  {
    id: '1.5',
    title: 'Environmental protection',
    chapters: [
      { id: '1.5.01', name: 'Environmental protection', totalQuestions: 45, completedQuestions: 0 },
    ],
  },
  {
    id: '1.6',
    title: 'Rules on the operation of the vehicles',
    chapters: [
      { id: '1.6.01', name: 'Rules on the operation of the vehicles', totalQuestions: 0, completedQuestions: 0 },
    ],
  },
  {
    id: '1.7',
    title: 'Technology',
    chapters: [
      { id: '1.7.01', name: 'Driving operation, driving physics, driving technique', totalQuestions: 2, completedQuestions: 0 },
    ],
  },
  {
    id: '1.8',
    title: 'Qualification and ability of drivers',
    chapters: [
      { id: '1.8.01', name: 'Qualification and ability of drivers', totalQuestions: 1, completedQuestions: 0 },
    ],
  },
  {
    id: '2.1',
    title: 'Danger teaching',
    chapters: [
      { id: '2.1.01', name: 'Basic forms of traffic behaviour', totalQuestions: 12, completedQuestions: 0 },
      { id: '2.1.02', name: 'Behaviour towards pedestrians', totalQuestions: 5, completedQuestions: 0 },
      { id: '2.1.03', name: 'Road and weather conditions', totalQuestions: 63, completedQuestions: 0 },
      { id: '2.1.04', name: 'Darkness and poor visibility', totalQuestions: 9, completedQuestions: 0 },
      { id: '2.1.05', name: 'Speed', totalQuestions: 15, completedQuestions: 0 },
      { id: '2.1.06', name: 'Overtaking', totalQuestions: 40, completedQuestions: 0 },
      { id: '2.1.07', name: 'Special traffic situations', totalQuestions: 58, completedQuestions: 0 },
      { id: '2.1.08', name: 'Motorway', totalQuestions: 28, completedQuestions: 0 },
      { id: '2.1.09', name: 'Alcohol, drugs, medication', totalQuestions: 2, completedQuestions: 0 },
      { id: '2.1.10', name: 'Fatigue, distraction', totalQuestions: 9, completedQuestions: 0 },
      { id: '2.1.11', name: 'Affective-emotional behaviour in road traffic', totalQuestions: 39, completedQuestions: 0 },
    ],
  },
  {
    id: '2.2',
    title: 'Behaviour in traffic',
    chapters: [
      { id: '2.2.02', name: 'Road use', totalQuestions: 14, completedQuestions: 0 },
      { id: '2.2.03', name: 'Speed', totalQuestions: 40, completedQuestions: 0 },
      { id: '2.2.04', name: 'Distance', totalQuestions: 21, completedQuestions: 0 },
      { id: '2.2.05', name: 'Overtaking', totalQuestions: 21, completedQuestions: 0 },
      { id: '2.2.06', name: 'Use of lanes by motor vehicles', totalQuestions: 2, completedQuestions: 0 },
      { id: '2.2.07', name: 'Use of lanes by motor vehicles', totalQuestions: 14, completedQuestions: 0 },
      { id: '2.2.09', name: 'Turning, turning and reversing', totalQuestions: 22, completedQuestions: 0 },
      { id: '2.2.12', name: 'Stopping and parking', totalQuestions: 18, completedQuestions: 0 },
      { id: '2.2.13', name: 'Parking time monitoring devices', totalQuestions: 5, completedQuestions: 0 },
      { id: '2.2.14', name: 'Duty of care', totalQuestions: 18, completedQuestions: 0 },
      { id: '2.2.15', name: 'Immobilisation and towing of vehicles', totalQuestions: 16, completedQuestions: 0 },
      { id: '2.2.16', name: 'Warning signs', totalQuestions: 2, completedQuestions: 0 },
      { id: '2.2.17', name: 'Lighting', totalQuestions: 30, completedQuestions: 0 },
      { id: '2.2.18', name: 'Motorways and motorways', totalQuestions: 41, completedQuestions: 0 },
      { id: '2.2.21', name: 'Passenger transport', totalQuestions: 40, completedQuestions: 0 },
      { id: '2.2.22', name: 'Load', totalQuestions: 59, completedQuestions: 0 },
      { id: '2.2.23', name: 'Other duties of the driver', totalQuestions: 97, completedQuestions: 0 },
      { id: '2.2.26', name: 'Behaviour at pedestrian crossings and towards pedestrians', totalQuestions: 1, completedQuestions: 0 },
      { id: '2.2.29', name: 'Excessive road use', totalQuestions: 4, completedQuestions: 0 },
      { id: '2.2.30', name: 'Sunday driving ban', totalQuestions: 7, completedQuestions: 0 },
      { id: '2.2.32', name: 'Traffic obstructions', totalQuestions: 8, completedQuestions: 0 },
      { id: '2.2.34', name: 'Accident', totalQuestions: 16, completedQuestions: 0 },
      { id: '2.2.37', name: 'Variable and steady light signals', totalQuestions: 7, completedQuestions: 0 },
      { id: '2.2.38', name: 'Vehicles with right of way', totalQuestions: 1, completedQuestions: 0 },
    ],
  },
  {
    id: '2.4',
    title: 'Traffic sign',
    chapters: [
      { id: '2.4.40', name: 'Danger sign', totalQuestions: 7, completedQuestions: 0 },
      { id: '2.4.41', name: 'Regulatory sign', totalQuestions: 24, completedQuestions: 0 },
      { id: '2.4.42', name: 'Directional sign', totalQuestions: 17, completedQuestions: 0 },
      { id: '2.4.43', name: 'Traffic facilities', totalQuestions: 1, completedQuestions: 0 },
    ],
  },
  {
    id: '2.5',
    title: 'Environmental protection',
    chapters: [
      { id: '2.5.01', name: 'Environmental protection', totalQuestions: 54, completedQuestions: 0 },
    ],
  },
  {
    id: '2.6',
    title: 'Rules on the operation of the vehicles',
    chapters: [
      { id: '2.6.01', name: 'Examination of the vehicles', totalQuestions: 13, completedQuestions: 0 },
      { id: '2.6.02', name: 'Admission to road traffic, vehicle documents, driving licence', totalQuestions: 65, completedQuestions: 0 },
      { id: '2.6.03', name: 'Trailer operation', totalQuestions: 32, completedQuestions: 0 },
      { id: '2.6.04', name: 'Driving and rest periods', totalQuestions: 32, completedQuestions: 0 },
      { id: '2.6.05', name: 'EC monitoring device', totalQuestions: 8, completedQuestions: 0 },
      { id: '2.6.06', name: 'Dimensions, weights and speed limiters', totalQuestions: 31, completedQuestions: 0 },
      { id: '2.6.07', name: 'Reading a road map and route planning', totalQuestions: 24, completedQuestions: 0 },
    ],
  },
  {
    id: '2.7',
    title: 'Technology',
    chapters: [
      { id: '2.7.01', name: 'Driving operation, driving physics, driving technique', totalQuestions: 169, completedQuestions: 0 },
      { id: '2.7.02', name: 'Fault detection, localisation of faults', totalQuestions: 96, completedQuestions: 0 },
      { id: '2.7.03', name: 'Combustion engine, fluids, fuel system, electrical system, ignition, power transmission', totalQuestions: 18, completedQuestions: 0 },
      { id: '2.7.04', name: 'Lubricants and antifreeze', totalQuestions: 8, completedQuestions: 0 },
      { id: '2.7.05', name: 'Use and maintenance of tyres', totalQuestions: 39, completedQuestions: 0 },
      { id: '2.7.06', name: 'Brake systems and cruise control', totalQuestions: 75, completedQuestions: 0 },
      { id: '2.7.07', name: 'Trailer coupling systems', totalQuestions: 31, completedQuestions: 0 },
      { id: '2.7.08', name: 'Maintenance of motor vehicles and timely arrangement of repairs', totalQuestions: 11, completedQuestions: 0 },
      { id: '2.7.09', name: 'Receipt, transport and delivery of goods', totalQuestions: 19, completedQuestions: 0 },
      { id: '2.7.10', name: 'Equipment of vehicles', totalQuestions: 16, completedQuestions: 0 },
    ],
  },
  {
    id: '2.8',
    title: 'Qualification and ability of truck drivers',
    chapters: [
      { id: '2.8.01', name: 'Qualification and ability of truck drivers', totalQuestions: 16, completedQuestions: 0 },
    ],
  },
];
